# Generated by Django 2.2 on 2019-05-06 17:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms_and_conditions',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='06', help_text='Mag alleen getallen bevatten', max_length=100, validators=[users.models.validate_phonenumber]),
            preserve_default=False,
        ),
    ]
