# Generated by Django 2.2 on 2019-05-01 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_email', models.EmailField(help_text='Email-address for correspondence related to your teacher profile.', max_length=254)),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=0)),
                ('profile_picture', models.ImageField(blank=True, upload_to='teacher_photos/%Y/%m/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
