# Generated by Django 2.2 on 2019-05-17 18:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_email', models.EmailField(blank=True, help_text='Als je een ander email adres wilt gebruiken voor je leraren account, vul dit dan in. Anders gebruiken we je gebruikersemail.', max_length=254)),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=0)),
                ('profile_picture', models.ImageField(blank=True, upload_to='teacher_photos/%Y/%m/%d')),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Wiskunde A'), (1, 'Wiskunde B'), (2, 'Natuurkunde'), (3, 'Scheikunde')]), blank=True, default=list, size=None)),
                ('hourprice', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
